### ISSUE TITLE
Array testing

### ISSUE THREAD

**Issue by dkwon1223** [dkwon1223/fitlit#17]
"On your last test, the line expect(expected).to.be.an("array").with.lengthOf(7); doesn’t actually test the contents of that array, which leaves a lot of room for a mistake to not get caught by a test. A good rule of thumb for testing arrays is to test:
- The length of the array
- The contents of the first element of the array
- The contents of the last element of the array"

**Comment by EthanDuvall** [comment]
Done and pull request has been put up
